name: Lib CI

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]
    tags: [ v* ]
jobs:
  build-gradle:
    name: Build
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: set Up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build with Gradle Wrapper
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: wrapper
          arguments: build

  publish-to-snapshot:
    name: Publish SNAPSHOT to sonatype.org
    needs: [ build-gradle ]
    # Runs only in main
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' &&  github.repository_owner == 'xatzipe'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish with Gradle Wrapper
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish --full-stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.OSSRH_GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}